name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3

    - name: Compiling using GCC
      run: cc -c *.c
      env:
        CC: gcc

    - name: Cleaning
      run: rm *.o

    - name: Compiling using Clang
      run: cc -c *.c
      env:
        CC: clang