name: Tripouille Tester

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3

    - name: Setting up the folder
      run: |
          git clone -n https://github.com/Tripouille/gnlTester.git
          cd gnlTester
          git reset --hard 2e28a6ce9454666c6670645a60a1b9b4404d0c65

    - name: Running tester
      run: make a
